control-version-fail

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -59,8 +59,14 @@ jobs:
         id: get_version
         run: |
           version=$(npx semantic-release --dry-run --tag "${{ env.base_version }}"| grep -oE 'next version is [0-9]+\.[0-9]+\.[0-9]+' | awk '{print $4}')
-          echo "Version: $version"
-          echo "version=$version" >> $GITHUB_ENV
+          # Check if the version is empty
+          if [[ -z "$version" ]]; then
+            echo "Error: Version could not be determined."
+            exit 1  # Fail the step
+          else
+            echo "Version: $version"
+            echo "version=$version" >> $GITHUB_ENV
+          fi
 
       - name: Build Docker Image with Version and Commit Hash
         run: |
